# Generated by Django 5.0.3 on 2024-03-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_category_categoria_alter_projetos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='owner',
            new_name='criador',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='created_date',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='email_respondavel',
            new_name='email_responsavel',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='picture',
            new_name='logo',
        ),
    ]
