# Generated by Django 5.0.3 on 2024-03-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projetos_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
