# Generated by Django 5.0.3 on 2024-04-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_projetos_imagem_1_projetos_imagem_2_projetos_texto_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='imagem_1',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='texto_1',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='texto_2',
        ),
    ]
