# Generated by Django 5.0.3 on 2024-04-03 18:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_remove_projetos_imagem_1_remove_projetos_imagem_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='corpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
